name: Build, Restore and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Bước 1: Lấy code từ repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Bước 2: Cài đặt .NET SDK
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      # Bước 3: Khôi phục các package NuGet
      - name: Restore dependencies
        run: dotnet restore ./TexifyLab/TexifyLab.slnx
      
      # Bước 4: Build project
      - name: Build project
        run: dotnet build ./TexifyLab/TexifyLab.slnx --configuration Release --no-restore
      
      # Bước 5: Chạy unit tests
      - name: Run unit tests
        run: dotnet test ./TexifyLab/TexifyLab.slnx --configuration Release --no-build --logger trx
      
      # Bước 6: (Tùy chọn) Upload kết quả test để xem sau
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
          retention-days: 7
  
  check-step:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "LABEL DATA => ${{ toJson(github.event.pull_request.labels.*.name) }}"

  build-texify-console-app:
    needs: build-and-test
    uses: ./.github/workflows/build-console-app.yml

  publish-nuget-package:
    needs: build-and-test
    uses: ./.github/workflows/publish-package.yml
    secrets: 
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  use-output:
    needs: publish-nuget-package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result from PUBLISH_PACKAGE JOB => ${{ toJson(needs.publish-nuget-package.outputs.publish_result) }}"