name: Multiply Numbers

on:
  workflow_call:
    inputs:
      a:
        type: string
        description: "First number"
        required: true
      b:
        type: string
        description: "Second number"
        required: true

jobs:
  multiply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nhan-2-so -f TexifyLab/ConsoleApp/Dockerfile TexifyLab/

      - name: Run multiplication
        id: multiply
        run: |
          docker run --rm nhan-2-so ${{ inputs.a }} ${{ inputs.b }} \
            | grep "^result=" \
            | sed 's/^result=/multiplication_result=/' \
            >> $GITHUB_OUTPUT

      - name: Show result
        run: echo "Result = ${{ steps.multiply.outputs.multiplication_result }}"
