name: Publish Package

on:
  workflow_call: # Thêm dòng này để cho phép workflow khác gọi nó
    secrets:     # Khai báo các secret cần dùng
      NUGET_API_KEY:
        required: true    
    outputs:
      publish_result:
        description: "JSON result of the publish job"
        value: ${{ jobs.publish.outputs.publish_result }}

  pull_request:
    types:
      - closed
    branches: [ "main"]

jobs:
  publish:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy package')
    runs-on: ubuntu-latest
    outputs:
      publish_result: ${{ steps.set-result.outputs.publish_result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./TexifyLab/TexifyLab.slnx
      
      - name: Pack NuGet package
        run: dotnet pack ./TexifyLab/TexifyLab.slnx --configuration Release --output ./nupkg
      
      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Set publish result output
        id: set-result
        run: |
          TIMESTAMP=$(date --utc +"%Y-%m-%dT%H:%M:%SZ")

          JSON_OUTPUT=$(jq -n \
            --arg jobId "${{ github.run_id }}-${{ github.job }}" \
            --arg ts "$TIMESTAMP" \
            --arg desc "publish okay" \
            '{jobId: $jobId, timestamp: $ts, description: $desc}')

          echo "publish_result<<EOF" >> "$GITHUB_OUTPUT"
          echo "$JSON_OUTPUT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  fallback-publish:
    if: github.event.pull_request.merged != true || !contains(github.event.pull_request.labels.*.name, 'deploy package')
    runs-on: ubuntu-latest
    steps:
      - name: Set publish result output with fallback
        id: set-result
        run: |
          TIMESTAMP=$(date --utc +"%Y-%m-%dT%H:%M:%SZ")

          JSON_OUTPUT=$(jq -n \
            --arg jobId "${{ github.run_id }}-${{ github.job }}" \
            --arg ts "$TIMESTAMP" \
            --arg desc "fallback, no publish" \
            '{jobId: $jobId, timestamp: $ts, description: $desc}')

          echo "publish_result<<EOF" >> "$GITHUB_OUTPUT"
          echo "$JSON_OUTPUT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"