name: Test hash-string action

on:
  workflow_call:
jobs:
  test-hash-string-action:
    runs-on: ubuntu-latest

    steps:
      - uses: tuantran0343/string-fingerprint@1.0.2
        id: test_hash
        with:
          value: "Billy"
          salty: "some_salt_here"
      - run: |
          echo "Input value: 'Billy'"
          echo "Input salty: 'some_salt_here'"
          echo "Hashed result is ${{ steps.test_hash.outputs.hashed }}"
