name: Use WorkFlow Run
on:

  workflow_run: 
    workflows: ['Try cache CI']
    types: 
        completed

jobs:
    
  use-workflow-run-sample:
    runs-on: ubuntu-latest
    steps:

      - name: Log something
        run: |
            echo 'hello, CI has been triggered me by workflow run' 