name: Varify Secret Run
on:

  workflow_call:
    inputs:
        title:
            type: string
            required: true

jobs:
    
  try-cache-ci:
    runs-on: ubuntu-latest
    steps:

      - name: Log title
        run: |
            echo ${{ inputs.title }}